### ISSUE TITLE
OpenHAB with username/password

### ISSUE THREAD

**Issue by dkrizic** [tommasomarchionni/homebridge-openHAB#39]
My OpenHAB is secured with a Username/Password, because I access it remotely via the Internet. Homebridge is unable to access my OpenHAB and I can't see a location where I can enter username/password.

Can this be added?

**Comment by gijoecool** [comment]
Can you add to the URL in the homebridge config? Example http[s]://[username]:[password]@[ip-address]:[port]/

**Comment by dkrizic** [comment]
That solves it, thank you!

**Comment by dkrizic** [comment]
After starting homebridge, I loads all my devices, but then I see this

`[10/16/2016, 4:09:17 PM] Homebridge is running on port 51826.
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: unexpected server response (401)
    at ClientRequest.response (/usr/lib/node_modules/homebridge-openhab/node_modules/ws/lib/WebSocket.js:694:15)
    at ClientRequest.g (events.js:260:16)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming](_http_client.js:433:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:103:23)
    at Socket.socketOnData (_http_client.js:322:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:153:18)
`

**Comment by matz666** [comment]
You must add a line with "user":
And a line with "password": 
In you config.json

**Comment by RafalLukawiecki** [comment]
Is it possible to configure the connection so it uses https rather than http, and so to port 8443? Just changing the port did not work. Many thanks for this very useful plug-in!
